export const COUNTRY_NAME_LIST = [
	{ idNumber: '-1', country: 'Northern Cyprus', id: '' },
	{ idNumber: '-2', country: 'Kosovo', id: '' },
	{ idNumber: '993', country: 'Somaliland', id: '' },
	{ idNumber: '004', country: 'Afghanistan', id: 'AF' },
	{ idNumber: '008', country: 'Albania', id: 'AL' },
	{ idNumber: '010', country: 'Antarctica', id: 'AQ' },
	{ idNumber: '012', country: 'Algeria', id: 'DZ' },
	{ idNumber: '016', country: 'American Samoa', id: 'AS' },
	{ idNumber: '020', country: 'Andorra', id: 'AD' },
	{ idNumber: '024', country: 'Angola', id: 'AO' },
	{ idNumber: '028', country: 'Antigua and Barbuda', id: 'AG' },
	{ idNumber: '031', country: 'Azerbaijan', id: 'AZ' },
	{ idNumber: '032', country: 'Argentina', id: 'AR' },
	{ idNumber: '036', country: 'Australia', id: 'AU' },
	{ idNumber: '040', country: 'Austria', id: 'AT' },
	{ idNumber: '044', country: 'Bahamas', id: 'BS' },
	{ idNumber: '048', country: 'Bahrain', id: 'BH' },
	{ idNumber: '050', country: 'Bangladesh', id: 'BD' },
	{ idNumber: '051', country: 'Armenia', id: 'AM' },
	{ idNumber: '052', country: 'Barbados', id: 'BB' },
	{ idNumber: '056', country: 'Belgium', id: 'BE' },
	{ idNumber: '060', country: 'Bermuda', id: 'BM' },
	{ idNumber: '064', country: 'Bhutan', id: 'BT' },
	{ idNumber: '068', country: 'Bolivia, Plurinational State of', id: 'BO' },
	{ idNumber: '070', country: 'Bosnia and Herzegovina', id: 'BA' },
	{ idNumber: '072', country: 'Botswana', id: 'BW' },
	{ idNumber: '074', country: 'Bouvet Island', id: 'BV' },
	{ idNumber: '076', country: 'Brazil', id: 'BR' },
	{ idNumber: '084', country: 'Belize', id: 'BZ' },
	{ idNumber: '086', country: 'British Indian Ocean Territory', id: 'IO' },
	{ idNumber: '090', country: 'Solomon Islands', id: 'SB' },
	{ idNumber: '092', country: 'Virgin Islands, British', id: 'VI' },
	{ idNumber: '096', country: 'Brunei Darussalam', id: 'BN' },
	{ idNumber: '100', country: 'Bulgaria', id: 'BG' },
	{ idNumber: '104', country: 'Myanmar', id: 'MM' },
	{ idNumber: '108', country: 'Burundi', id: 'BI' },
	{ idNumber: '112', country: 'Belarus', id: 'BY' },
	{ idNumber: '116', country: 'Cambodia', id: 'KH' },
	{ idNumber: '120', country: 'Cameroon', id: 'CM' },
	{ idNumber: '124', country: 'Canada', id: 'CA' },
	{ idNumber: '132', country: 'Cape Verde', id: 'CV' },
	{ idNumber: '136', country: 'Cayman Islands', id: 'KY' },
	{ idNumber: '140', country: 'Central African Republic', id: 'CF' },
	{ idNumber: '144', country: 'Sri Lanka', id: 'LK' },
	{ idNumber: '148', country: 'Chad', id: 'TD' },
	{ idNumber: '152', country: 'Chile', id: 'CL' },
	{ idNumber: '156', country: 'China', id: 'CN' },
	{ idNumber: '158', country: 'Taiwan, Province of China', id: 'TW' },
	{ idNumber: '162', country: 'Christmas Island', id: 'CX' },
	{ idNumber: '166', country: 'Cocos (Keeling) Islands', id: 'CC' },
	{ idNumber: '170', country: 'Colombia', id: 'CO' },
	{ idNumber: '174', country: 'Comoros', id: 'KM' },
	{ idNumber: '175', country: 'Mayotte', id: 'YT' },
	{ idNumber: '178', country: 'Congo', id: 'CG' },
	{
		idNumber: '180',
		country: 'Congo, the Democratic Republic of the',
		id: 'CD'
	},
	{ idNumber: '184', country: 'Cook Islands', id: 'CK' },
	{ idNumber: '188', country: 'Costa Rica', id: 'CR' },
	{ idNumber: '191', country: 'Croatia', id: 'HR' },
	{ idNumber: '192', country: 'Cuba', id: 'CU' },
	{ idNumber: '196', country: 'Cyprus', id: 'CY' },
	{ idNumber: '203', country: 'Czech Republic', id: 'CZ' },
	{ idNumber: '204', country: 'Benin', id: 'BJ' },
	{ idNumber: '208', country: 'Denmark', id: 'DK' },
	{ idNumber: '212', country: 'Dominica', id: 'DM' },
	{ idNumber: '214', country: 'Dominican Republic', id: 'DO' },
	{ idNumber: '218', country: 'Ecuador', id: 'EC' },
	{ idNumber: '222', country: 'El Salvador', id: 'SV' },
	{ idNumber: '226', country: 'Equatorial Guinea', id: 'GQ' },
	{ idNumber: '231', country: 'Ethiopia', id: 'ET' },
	{ idNumber: '232', country: 'Eritrea', id: 'ER' },
	{ idNumber: '233', country: 'Estonia', id: 'EE' },
	{ idNumber: '234', country: 'Faroe Islands', id: 'FO' },
	{ idNumber: '238', country: 'Falkland Islands (Malvinas)', id: 'FK' },
	{
		idNumber: '239',
		country: 'South Georgia and the South Sandwich Islands',
		id: 'GS'
	},
	{ idNumber: '242', country: 'Fiji', id: 'FJ' },
	{ idNumber: '246', country: 'Finland', id: 'FI' },
	{ idNumber: '248', country: 'Åland Islands', id: 'AX' },
	{ idNumber: '250', country: 'France', id: 'FR' },
	{ idNumber: '254', country: 'French Guiana', id: 'GF' },
	{ idNumber: '258', country: 'French Polynesia', id: 'PF' },
	{ idNumber: '260', country: 'French Southern Territories', id: 'TF' },
	{ idNumber: '262', country: 'Djibouti', id: 'DJ' },
	{ idNumber: '266', country: 'Gabon', id: 'GA' },
	{ idNumber: '268', country: 'Georgia', id: 'GE' },
	{ idNumber: '270', country: 'Gambia', id: 'GM' },
	{ idNumber: '275', country: 'Palestinian Territory, Occupied', id: 'PS' },
	{ idNumber: '276', country: 'Germany', id: 'DE' },
	{ idNumber: '288', country: 'Ghana', id: 'GH' },
	{ idNumber: '292', country: 'Gibraltar', id: 'GI' },
	{ idNumber: '296', country: 'Kiribati', id: 'KI' },
	{ idNumber: '300', country: 'Greece', id: 'GR' },
	{ idNumber: '304', country: 'Greenland', id: 'GL' },
	{ idNumber: '308', country: 'Grenada', id: 'GD' },
	{ idNumber: '312', country: 'Guadeloupe', id: 'GP' },
	{ idNumber: '316', country: 'Guam', id: 'GU' },
	{ idNumber: '320', country: 'Guatemala', id: 'GT' },
	{ idNumber: '324', country: 'Guinea', id: 'GN' },
	{ idNumber: '328', country: 'Guyana', id: 'GY' },
	{ idNumber: '332', country: 'Haiti', id: 'HT' },
	{ idNumber: '334', country: 'Heard Island and McDonald Islands', id: 'HM' },
	{ idNumber: '336', country: 'Holy See (Vatican City State)', id: 'VA' },
	{ idNumber: '340', country: 'Honduras', id: 'HN' },
	{ idNumber: '344', country: 'Hong Kong', id: 'HK' },
	{ idNumber: '348', country: 'Hungary', id: 'HU' },
	{ idNumber: '352', country: 'Iceland', id: 'IS' },
	{ idNumber: '356', country: 'India', id: 'IN' },
	{ idNumber: '360', country: 'Indonesia', id: 'ID' },
	{ idNumber: '364', country: 'Iran, Islamic Republic of', id: 'IR' },
	{ idNumber: '368', country: 'Iraq', id: 'IQ' },
	{ idNumber: '372', country: 'Ireland', id: 'IE' },
	{ idNumber: '376', country: 'Israel', id: 'IL' },
	{ idNumber: '380', country: 'Italy', id: 'IT' },
	{ idNumber: '384', country: 'Côte d\'Ivoire', id: 'CI' },
	{ idNumber: '388', country: 'Jamaica', id: 'JM' },
	{ idNumber: '392', country: 'Japan', id: 'JP' },
	{ idNumber: '398', country: 'Kazakhstan', id: 'KZ' },
	{ idNumber: '400', country: 'Jordan', id: 'JO' },
	{ idNumber: '404', country: 'Kenya', id: 'JE' },
	{
		idNumber: '408',
		country: 'Korea, Democratic People\'s Republic of',
		id: 'KP'
	},
	{ idNumber: '410', country: 'Korea, Republic of', id: 'KR' },
	{ idNumber: '414', country: 'Kuwait', id: 'KW' },
	{ idNumber: '417', country: 'Kyrgyzstan', id: 'KG' },
	{ idNumber: '418', country: 'Lao People\'s Democratic Republic', id: 'LA' },
	{ idNumber: '422', country: 'Lebanon', id: 'LB' },
	{ idNumber: '426', country: 'Lesotho', id: 'LS' },
	{ idNumber: '428', country: 'Latvia', id: 'LV' },
	{ idNumber: '430', country: 'Liberia', id: 'LR' },
	{ idNumber: '434', country: 'Libya', id: 'LY' },
	{ idNumber: '438', country: 'Liechtenstein', id: 'LI' },
	{ idNumber: '440', country: 'Lithuania', id: 'LT' },
	{ idNumber: '442', country: 'Luxembourg', id: 'LU' },
	{ idNumber: '446', country: 'Macao', id: 'MO' },
	{ idNumber: '450', country: 'Madagascar', id: 'MG' },
	{ idNumber: '454', country: 'Malawi', id: 'MW' },
	{ idNumber: '458', country: 'Malaysia', id: 'MY' },
	{ idNumber: '462', country: 'Maldives', id: 'MV' },
	{ idNumber: '466', country: 'Mali', id: 'ML' },
	{ idNumber: '470', country: 'Malta', id: 'MT' },
	{ idNumber: '474', country: 'Martinique', id: 'MQ' },
	{ idNumber: '478', country: 'Mauritania', id: 'MR' },
	{ idNumber: '480', country: 'Mauritius', id: 'MU' },
	{ idNumber: '484', country: 'Mexico', id: 'MX' },
	{ idNumber: '492', country: 'Monaco', id: 'MC' },
	{ idNumber: '496', country: 'Mongolia', id: 'MN' },
	{ idNumber: '498', country: 'Moldova, Republic of', id: 'MD' },
	{ idNumber: '499', country: 'Montenegro', id: 'ME' },
	{ idNumber: '500', country: 'Montserrat', id: 'MS' },
	{ idNumber: '504', country: 'Morocco', id: 'MA' },
	{ idNumber: '508', country: 'Mozambique', id: 'MZ' },
	{ idNumber: '512', country: 'Oman', id: 'OM' },
	{ idNumber: '516', country: 'Namibia', id: 'NA' },
	{ idNumber: '520', country: 'Nauru', id: 'NR' },
	{ idNumber: '524', country: 'Nepal', id: 'NP' },
	{ idNumber: '528', country: 'Netherlands', id: 'NL' },
	{ idNumber: '531', country: 'Curaçao', id: 'CW' },
	{ idNumber: '533', country: 'Aruba', id: 'AW' },
	{ idNumber: '534', country: 'Sint Maarten (Dutch part)', id: 'MF' },
	{ idNumber: '535', country: 'Bonaire, Sint Eustatius and Saba', id: 'AN' },
	{ idNumber: '540', country: 'New Caledonia', id: 'NC' },
	{ idNumber: '548', country: 'Vanuatu', id: 'VU' },
	{ idNumber: '554', country: 'New Zealand', id: 'NZ' },
	{ idNumber: '558', country: 'Nicaragua', id: 'NI' },
	{ idNumber: '562', country: 'Niger', id: 'NE' },
	{ idNumber: '566', country: 'Nigeria', id: 'NG' },
	{ idNumber: '570', country: 'Niue', id: 'NU' },
	{ idNumber: '574', country: 'Norfolk Island', id: 'NF' },
	{ idNumber: '578', country: 'Norway', id: 'NO' },
	{ idNumber: '580', country: 'Northern Mariana Islands', id: 'MP' },
	{
		idNumber: '581',
		country: 'United States Minor Outlying Islands',
		id: 'UM'
	},
	{ idNumber: '583', country: 'Micronesia, Federated States of', id: 'FM' },
	{ idNumber: '584', country: 'Marshall Islands', id: 'MH' },
	{ idNumber: '585', country: 'Palau', id: 'PW' },
	{ idNumber: '586', country: 'Pakistan', id: 'PK' },
	{ idNumber: '591', country: 'Panama', id: 'PA' },
	{ idNumber: '598', country: 'Papua New Guinea', id: 'PNG' },
	{ idNumber: '600', country: 'Paraguay', id: 'PY' },
	{ idNumber: '604', country: 'Peru', id: 'PE' },
	{ idNumber: '608', country: 'Philippines', id: 'PH' },
	{ idNumber: '612', country: 'Pitcairn', id: 'PN' },
	{ idNumber: '616', country: 'Poland', id: 'PL' },
	{ idNumber: '620', country: 'Portugal', id: 'PT' },
	{ idNumber: '624', country: 'Guinea-Bissau', id: 'GW' },
	{ idNumber: '626', country: 'Timor-Leste', id: 'TL' },
	{ idNumber: '630', country: 'Puerto Rico', id: 'PR' },
	{ idNumber: '634', country: 'Qatar', id: 'QA' },
	{ idNumber: '638', country: 'Réunion', id: 'RE' },
	{ idNumber: '642', country: 'Romania', id: 'RO' },
	{ idNumber: '643', country: 'Russian Federation', id: 'RU' },
	{ idNumber: '646', country: 'Rwanda', id: 'RW' },
	{ idNumber: '652', country: 'Saint Barthélemy', id: 'BL' },
	{
		idNumber: '654',
		country: 'Saint Helena, Ascension and Tristan da Cunha',
		id: 'SH'
	},
	{ idNumber: '659', country: 'Saint Kitts and Nevis', id: 'KN' },
	{ idNumber: '660', country: 'Anguilla', id: 'AI' },
	{ idNumber: '662', country: 'Saint Lucia', id: 'LC' },
	{ idNumber: '663', country: 'Saint Martin (French part)', id: 'MF' },
	{ idNumber: '666', country: 'Saint Pierre and Miquelon', id: 'PM' },
	{ idNumber: '670', country: 'Saint Vincent and the Grenadines', id: 'VS' },
	{ idNumber: '674', country: 'San Marino', id: 'SM' },
	{ idNumber: '678', country: 'Sao Tome and Principe', id: 'ST' },
	{ idNumber: '682', country: 'Saudi Arabia', id: 'SA' },
	{ idNumber: '686', country: 'Senegal', id: 'SN' },
	{ idNumber: '688', country: 'Serbia', id: 'RS' },
	{ idNumber: '690', country: 'Seychelles', id: 'SC' },
	{ idNumber: '694', country: 'Sierra Leone', id: 'SL' },
	{ idNumber: '702', country: 'Singapore', id: 'SG' },
	{ idNumber: '703', country: 'Slovakia', id: 'SK' },
	{ idNumber: '704', country: 'Viet Nam', id: 'VN' },
	{ idNumber: '705', country: 'Slovenia', id: 'SI' },
	{ idNumber: '706', country: 'Somalia', id: 'SO' },
	{ idNumber: '710', country: 'South Africa', id: 'ZA' },
	{ idNumber: '716', country: 'Zimbabwe', id: 'ZA' },
	{ idNumber: '724', country: 'Spain', id: 'ES' },
	{ idNumber: '728', country: 'South Sudan', id: 'SS' },
	{ idNumber: '729', country: 'Sudan', id: 'SD' },
	{ idNumber: '732', country: 'Western Sahara', id: 'EH' },
	{ idNumber: '740', country: 'Suriname', id: 'SR' },
	{ idNumber: '744', country: 'Svalbard and Jan Mayen', id: 'SJ' },
	{ idNumber: '748', country: 'Swaziland', id: 'SZ' },
	{ idNumber: '752', country: 'Sweden', id: 'SE' },
	{ idNumber: '756', country: 'Switzerland', id: 'CH' },
	{ idNumber: '760', country: 'Syrian Arab Republic', id: 'SY' },
	{ idNumber: '762', country: 'Tajikistan', id: 'TJ' },
	{ idNumber: '764', country: 'Thailand', id: 'TH' },
	{ idNumber: '768', country: 'Togo', id: 'TG' },
	{ idNumber: '772', country: 'Tokelau', id: 'TK' },
	{ idNumber: '776', country: 'Tonga', id: 'TO' },
	{ idNumber: '780', country: 'Trinidad and Tobago', id: 'TT' },
	{ idNumber: '784', country: 'United Arab Emirates', id: 'AE' },
	{ idNumber: '788', country: 'Tunisia', id: 'TN' },
	{ idNumber: '792', country: 'Turkey', id: 'TR' },
	{ idNumber: '795', country: 'Turkmenistan', id: 'TM' },
	{ idNumber: '796', country: 'Turks and Caicos Islands', id: 'TC' },
	{ idNumber: '798', country: 'Tuvalu', id: 'TV' },
	{ idNumber: '800', country: 'Uganda', id: 'UG' },
	{ idNumber: '804', country: 'Ukraine', id: 'UA' },
	{
		idNumber: '807',
		country: 'Macedonia, the former Yugoslav Republic of',
		id: 'MK'
	},
	{ idNumber: '818', country: 'Egypt', id: 'EG' },
	{ idNumber: '826', country: 'United Kingdom', id: 'GB' },
	{ idNumber: '831', country: 'Guernsey', id: 'GG' },
	{ idNumber: '832', country: 'Jersey', id: 'JE' },
	{ idNumber: '833', country: 'Isle of Man', id: 'IM' },
	{ idNumber: '834', country: 'Tanzania, United Republic of', id: 'TZ' },
	{ idNumber: '840', country: 'United States', id: 'US' },
	{ idNumber: '850', country: 'Virgin Islands, U.S.', id: 'VI' },
	{ idNumber: '854', country: 'Burkina Faso', id: 'BF' },
	{ idNumber: '858', country: 'Uruguay', id: 'UY' },
	{ idNumber: '860', country: 'Uzbekistan', id: 'UZ' },
	{ idNumber: '862', country: 'Venezuela, Bolivarian Republic of', id: 'VE' },
	{ idNumber: '876', country: 'Wallis and Futuna', id: 'WF' },
	{ idNumber: '882', country: 'Samoa', id: '' },
	{ idNumber: '887', country: 'Yemen', id: 'YE' },
	{ idNumber: '894', country: 'Zambia', id: 'ZM' }
];
